config/routes.rb
# typed: strict
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # Put this at the top for ~performance~
  root 'home#index'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  get 'home/index'

  resources :games do
    get :search, on: :collection
    post :add_game_to_library, on: :member
    delete :remove_game_from_library, on: :member
    delete :remove_cover, on: :member
    post :favorite, on: :member
    delete :unfavorite, on: :member
    get :favorited, on: :member
    # Path like `/games/:id/merge/:game_b_id`
    post :merge, on: :member, path: 'merge/:game_b_id'

    post :add_to_wikidata_blocklist, on: :member
  end

  resources :game_purchases, except: [:edit, :new] do
    post :bulk_update, on: :collection
  end

  resources :users do
    get :index, on: :collection
    get :search, on: :collection
    get :show, on: :member
    get :statistics, on: :member
    get :activity, on: :member
    get '/compare/:user_id...:other_user_id', as: :compare, action: :compare, on: :collection
    post :update_role, on: :member
    delete :remove_avatar, on: :member
    post :connect_steam, on: :member
    delete :disconnect_steam, on: :member
    post :steam_import, on: :member
    delete :reset_game_library, on: :member

    get :favorites, on: :member
    get :following, on: :member
    get :followers, on: :member
    post :follow, to: 'relationships#create'
    delete :unfollow, to: 'relationships#destroy'
    post :reset_token, on: :collection
    post :ban, on: :member
    post :unban, on: :member
  end

  namespace :activity do
    get :global, as: '/', path: '/'
    get :following
  end

  namespace :admin do
    get :dashboard, as: '/', path: '/'
    get :wikidata_blocklist, path: 'wikidata'
    delete :remove_from_wikidata_blocklist, path: 'wikidata/:wikidata_id/remove'

    get :new_steam_blocklist, path: 'steam/new'
    get :steam_blocklist, path: 'steam'
    post :add_to_steam_blocklist, path: 'steam'
    delete :remove_from_steam_blocklist, path: 'steam/:steam_app_id/remove'

    get :games_without_wikidata_ids

    resources :unmatched_games, param: :external_service_id, only: [:index, :destroy]
  end

  resources :events, only: :destroy

  resources :platforms do
    get :search, on: :collection
  end

  resources :engines do
    get :search, on: :collection
  end

  resources :genres do
    get :search, on: :collection
  end

  resources :companies do
    get :search, on: :collection
  end

  resources :series do
    get :search, on: :collection
  end

  resources :stores do
    get :search, on: :collection
  end

  namespace :search do
    get :index, as: '/', path: '/'
  end

  namespace :settings do
    get :profile, as: '/', path: '/'
    get :account
    get :import
    get :export
    get :export_as_json
    get :api_token, defaults: { format: :json }
  end

  scope :settings do
    # This is contributed by Doorkeeper, but Sorbet doesn't know that so we have to hack around it.
    T.unsafe(self).use_doorkeeper do
      T.unsafe(self).controllers applications: 'oauth/applications',
                                 authorized_applications: 'oauth/authorized_applications',
                                 authorizations: 'oauth/authorizations'
    end
  end

  # Implement the .well-known/change-password URL.
  get '.well-known/change-password', to: redirect('/settings/account')

  get '/about', to: 'static_pages#about'

  # For exposing the OpenSearch XML definition
  get '/opensearch', to: 'static_pages#opensearch', defaults: { format: :xml }

  # API routes
  get '/graphiql', to: 'static_pages#graphiql'
  # Execute GraphQL queries posted to '/graphql'.
  post "/graphql", to: "graphql#execute"
end

app/controllers/platforms_controller.rb
# typed: true
class PlatformsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @platforms = Platform.order(:id).page helpers.page_param
    skip_policy_scope
  end

  def show
    @platform = Platform.find(params[:id])
    skip_authorization

    @games = @platform.games
                      .with_attached_cover
                      .includes(:platforms, :developers)
                      .page helpers.page_param

    respond_to do |format|
      format.html
      format.json { render json: @platform }
    end
  end

  def new
    @platform = Platform.new
    authorize @platform
  end

  def edit
    @platform = Platform.find(params[:id])
    authorize @platform
  end

  def create
    @platform = Platform.new(platform_params)
    authorize @platform
    if @platform.save
      redirect_to @platform, success: "#{@platform.name} was successfully created."
    else
      flash.now[:error] = "Unable to save platform."
      render :new
    end
  end

  def update
    @platform = Platform.find(params[:id])
    authorize @platform

    if @platform.update(platform_params)
      redirect_to @platform, success: "#{@platform.name} was successfully updated."
    else
      flash.now[:error] = "Unable to update platform."
      render :edit
    end
  end

  def destroy
    @platform = Platform.find(params[:id])
    authorize @platform
    @platform.destroy
    redirect_to platforms_url, success: "Platform was successfully deleted."
  end

  def search
    if params[:query].present?
      @platforms = Platform.search(params[:query]).page(helpers.page_param)
    else
      @platforms = Platform.none.page(helpers.page_param)
    end

    authorize @platforms

    respond_to do |format|
      format.json { render json: @platforms }
    end
  end

  private

  sig { returns(ActionController::Parameters) }
  def platform_params
    params.typed_require(:platform).permit(
      :name,
      :wikidata_id
    )
  end
end

app/views/platforms/_form.html.erb
<%= form_for @platform do |f| %>
  <div class="field">
    <%= f.label :name, "Platform name", class: "label" %>
    <div class="control">
      <%= f.text_field :name, autocomplete: "off", class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :wikidata_id, "Wikidata ID", class: "label" %>
    <div class="control">
      <%= f.number_field :wikidata_id, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= f.submit "Submit", class: "button is-primary" %>
    <%= link_to("Cancel", cancel_path, class: "button") %>
  </div>
<% end %>

app/views/platforms/edit.html.erb
<% content_for :title, "Edit #{@platform.name}" %>

<h1 class="title">Edit <%= @platform.name %></h1>

<%= render 'form', cancel_path: platform_path(@platform.id) %>

app/views/platforms/index.html.erb
<% content_for :title, "Platforms" %>
<% content_for :description, "All game platforms available on vglist." %>

<h1 class="title">Platforms</h1>

<% if policy(@platforms).create? %>
  <p><%= link_to("Create a new platform", new_platform_path, class: 'button is-fullwidth-mobile mb-10') %></p>
<% end %>

<ul>
  <% @platforms.each do |platform| %>
    <li><%= link_to(platform.name, platform_path(platform.id)) %></li>
  <% end %>
</ul>

<%= paginate @platforms %>

app/views/platforms/new.html.erb
<% content_for :title, "Create a new platform" %>

<h1 class="title">Create a new platform</h1>

<%= render 'form', cancel_path: platforms_path %>

app/views/platforms/show.html.erb
<% content_for :title, @platform.name %>
<% content_for :description, "#{@platform.name} on vglist" %>

<h1 class="title"><%= @platform.name %></h1>

<% if policy(@platform).update? || policy(@platform).destroy? %>
  <div class="field buttons">
    <% if policy(@platform).update? %>
      <%= link_to("Edit", edit_platform_path(@platform.id), class: "button is-fullwidth-mobile mr-0-mobile") %>
    <% end %>
    <% if policy(@platform).destroy? %>
      <%= link_to("Delete", platform_path(@platform.id), method: :delete, data: { confirm: "You sure?" }, class: "button is-fullwidth-mobile is-danger") %>
    <% end %>
  </div>
<% end %>

<% unless @platform.wikidata_id.blank? %>
  <%= link_to 'Wikidata', "https://www.wikidata.org/wiki/Q#{@platform.wikidata_id}" %>
<% end %>

<% if !@games.blank? %>
  <div class="game-card-list mt-20">
    <% @games.each do |game| %>
      <%= render 'shared/game_card', game: game %>
    <% end %>
  </div>

  <%= paginate @games %>
<% else %>
  <p class='has-text-centered mt-50 has-text-muted'>This platform doesn't have any games yet.
<% end%>