config/routes.rb
# typed: strict
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # Put this at the top for ~performance~
  root 'home#index'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  get 'home/index'

  resources :games do
    get :search, on: :collection
    post :add_game_to_library, on: :member
    delete :remove_game_from_library, on: :member
    delete :remove_cover, on: :member
    post :favorite, on: :member
    delete :unfavorite, on: :member
    get :favorited, on: :member
    # Path like `/games/:id/merge/:game_b_id`
    post :merge, on: :member, path: 'merge/:game_b_id'

    post :add_to_wikidata_blocklist, on: :member
  end

  resources :game_purchases, except: [:edit, :new] do
    post :bulk_update, on: :collection
  end

  resources :users do
    get :index, on: :collection
    get :search, on: :collection
    get :show, on: :member
    get :statistics, on: :member
    get :activity, on: :member
    get '/compare/:user_id...:other_user_id', as: :compare, action: :compare, on: :collection
    post :update_role, on: :member
    delete :remove_avatar, on: :member
    post :connect_steam, on: :member
    delete :disconnect_steam, on: :member
    post :steam_import, on: :member
    delete :reset_game_library, on: :member

    get :favorites, on: :member
    get :following, on: :member
    get :followers, on: :member
    post :follow, to: 'relationships#create'
    delete :unfollow, to: 'relationships#destroy'
    post :reset_token, on: :collection
    post :ban, on: :member
    post :unban, on: :member
  end

  namespace :activity do
    get :global, as: '/', path: '/'
    get :following
  end

  namespace :admin do
    get :dashboard, as: '/', path: '/'
    get :wikidata_blocklist, path: 'wikidata'
    delete :remove_from_wikidata_blocklist, path: 'wikidata/:wikidata_id/remove'

    get :new_steam_blocklist, path: 'steam/new'
    get :steam_blocklist, path: 'steam'
    post :add_to_steam_blocklist, path: 'steam'
    delete :remove_from_steam_blocklist, path: 'steam/:steam_app_id/remove'

    get :games_without_wikidata_ids

    resources :unmatched_games, param: :external_service_id, only: [:index, :destroy]
  end

  resources :events, only: :destroy

  resources :platforms do
    get :search, on: :collection
  end

  resources :engines do
    get :search, on: :collection
  end

  resources :genres do
    get :search, on: :collection
  end

  resources :companies do
    get :search, on: :collection
  end

  resources :series do
    get :search, on: :collection
  end

  resources :stores do
    get :search, on: :collection
  end

  namespace :search do
    get :index, as: '/', path: '/'
  end

  namespace :settings do
    get :profile, as: '/', path: '/'
    get :account
    get :import
    get :export
    get :export_as_json
    get :api_token, defaults: { format: :json }
  end

  scope :settings do
    # This is contributed by Doorkeeper, but Sorbet doesn't know that so we have to hack around it.
    T.unsafe(self).use_doorkeeper do
      T.unsafe(self).controllers applications: 'oauth/applications',
                                 authorized_applications: 'oauth/authorized_applications',
                                 authorizations: 'oauth/authorizations'
    end
  end

  # Implement the .well-known/change-password URL.
  get '.well-known/change-password', to: redirect('/settings/account')

  get '/about', to: 'static_pages#about'

  # For exposing the OpenSearch XML definition
  get '/opensearch', to: 'static_pages#opensearch', defaults: { format: :xml }

  # API routes
  get '/graphiql', to: 'static_pages#graphiql'
  # Execute GraphQL queries posted to '/graphql'.
  post "/graphql", to: "graphql#execute"
end

app/models/store.rb
# typed: strict
class Store < ApplicationRecord
  include Searchable

  has_many :game_purchase_stores
  has_many :game_purchases, through: :game_purchase_stores, source: :game_purchase

  validates :name,
    presence: true,
    length: { maximum: 120 }

  searchable :name
end

app/controllers/stores_controller.rb
# typed: true
class StoresController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @stores = Store.order(:id).page helpers.page_param
    skip_policy_scope
  end

  def show
    @store = Store.find(params[:id])
    skip_authorization

    respond_to do |format|
      format.html
      format.json { render json: @store }
    end
  end

  def new
    @store = Store.new
    authorize @store
  end

  def edit
    @store = Store.find(params[:id])
    authorize @store
  end

  def create
    @store = Store.new(store_params)
    authorize @store

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html do
          flash.now[:error] = "Unable to create store."
          render :new
        end
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @store = Store.find(params[:id])
    authorize @store

    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html do
          flash.now[:error] = "Unable to update store."
          render :edit
        end
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @store = Store.find(params[:id])
    authorize @store
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    if params[:query].present?
      @stores = Store.search(params[:query]).page(helpers.page_param)
    else
      @stores = Store.none.page(helpers.page_param)
    end

    authorize @stores

    respond_to do |format|
      format.json { render json: @stores }
    end
  end

  private

  sig { returns(ActionController::Parameters) }
  def store_params
    params.typed_require(:store).permit(
      :name
    )
  end
end

app/views/stores/_form.html.erb
<%= form_for @store do |f| %>
  <div class="field">
    <%= f.label :name, "Store name", class: "label" %>
    <div class="control">
      <%= f.text_field :name, autocomplete: "off", class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= f.submit "Submit", class: "button is-primary" %>
    <%= link_to("Cancel", cancel_path, class: "button") %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<% content_for :title, "Edit #{@store.name}" %>

<h1 class="title">Edit <%= @store.name %></h1>

<%= render 'form', cancel_path: store_path(@store.id) %>

app/views/stores/index.html.erb
<% content_for :title, "Stores" %>
<% content_for :description, "All game stores on vglist." %>

<h1 class="title">Stores</h1>

<% if policy(@stores).create? %>
  <p><%= link_to("Create a new store", new_store_path, class: 'button is-fullwidth-mobile mb-10') %></p>
<% end %>

<ul>
  <% @stores.each do |store| %>
    <li><%= link_to(store.name, store_path(store.id)) %></li>
  <% end %>
</ul>

<%= paginate @stores %>

app/views/stores/new.html.erb
<% content_for :title, "Create a new store" %>

<h1 class="title">Create a new store</h1>

<%= render 'form', cancel_path: stores_path %>

app/views/stores/show.html.erb
<% content_for :title, @store.name %>
<% content_for :description, "#{@store.name} on vglist" %>

<h1 class="title"><%= @store.name %></h1>

<% if policy(@store).edit? || policy(@store).destroy? %>
  <div class="field buttons">
    <% if policy(@store).edit? %>
      <%= link_to("Edit", edit_store_path(@store.id), class: "button is-fullwidth-mobile mr-0-mobile") %>
    <% end %>
    <% if policy(@store).destroy? %>
      <%= link_to("Delete", store_path(@store.id), method: :delete, data: { confirm: "You sure?" }, class: "button is-fullwidth-mobile is-danger") %>
    <% end %>
  </div>
<% end %>